import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Factory, ScanLine, Warehouse, PackageCheck } from 'lucide-react';
import { SectionHeading } from './section-heading';
const imgs=[
'https://images.unsplash.com/photo-1567521464027-f127ff144326?auto=format&fit=crop&w=1600&q=90',
'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1000&q=90',
'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=1000&q=90'];
export function InfrastructureSection(){return <section className="section-pad bg-[#0d3324] text-white"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 lg:grid-cols-[1.15fr_.85fr] lg:px-9"><div className="grid min-h-[520px] grid-cols-[1.35fr_.65fr] gap-3"><div className="relative overflow-hidden rounded-2xl"><Image src={imgs[0]} alt="Industrial processing facility" fill sizes="55vw" className="object-cover transition duration-700 hover:scale-105"/></div><div className="grid gap-3"><div className="relative overflow-hidden rounded-2xl"><Image src={imgs[1]} alt="Warehouse and export logistics" fill sizes="25vw" className="object-cover"/></div><div className="relative overflow-hidden rounded-2xl"><Image src={imgs[2]} alt="Industrial quality processing environment" fill sizes="25vw" className="object-cover"/></div></div></div><div className="lg:pl-5"><SectionHeading eyebrow="INFRASTRUCTURE" title="Built for Quality. Designed for Scale." description="Advanced processing, controlled handling, modern sorting and export-ready packaging support consistent quality across bulk orders." light/><div className="mt-8 grid grid-cols-2 gap-3">{[[Factory,'Advanced Processing'],[ScanLine,'Optical Sorting'],[Warehouse,'Controlled Storage'],[PackageCheck,'Export Packaging']].map(([Icon,label])=><div key={String(label)} className="rounded-xl border border-white/15 bg-white/[.055] p-4"><Icon size={21} className="text-[#e2be5d]"/><strong className="mt-3 block text-[12px]">{String(label)}</strong></div>)}</div><Link href="/infrastructure" className="mt-7 inline-flex items-center gap-2 text-[12px] font-bold text-[#efcf75]">Explore Infrastructure <ArrowRight size={14}/></Link></div></div></section>}
