import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, Check } from 'lucide-react';
import { getProduct, products } from '@/data/products';
import { EnquirySection } from '@/components/enquiry-section';
export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getProduct(slug);return p?{title:p.name,description:p.description,alternates:{canonical:`/products/${p.slug}`}}:{title:'Product'}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=getProduct(slug);if(!p)notFound();const schema={'@context':'https://schema.org','@type':'Product',name:p.name,description:p.description,category:p.category,brand:{'@type':'Brand',name:'Shree Krishna Exports'}};return <><section className="pt-[78px]"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-16 lg:grid-cols-2 lg:px-9 lg:py-24"><div className="relative aspect-square overflow-hidden rounded-[28px] bg-[#f5f1e6]"><Image src={p.image} alt={p.name} fill priority sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div><div className="flex flex-col justify-center"><p className="eyebrow text-[#0B4A2B]">{p.category}</p><h1 className="mt-3 font-serif text-[clamp(3.5rem,6vw,6rem)] font-semibold leading-[.88] tracking-[-.04em]">{p.name}</h1><p className="mt-6 max-w-xl text-[15px] leading-7 text-[#667168]">{p.description}</p><div className="mt-8"><h2 className="text-xs font-bold uppercase tracking-[.15em] text-[#0B4A2B]">Available variants</h2><div className="mt-3 flex flex-wrap gap-2">{p.variants.map(v=><span key={v} className="rounded-full border border-[#d9d1bd] bg-[#FAF8F2] px-4 py-2 text-[11px] font-semibold">{v}</span>)}</div></div><div className="mt-8 grid gap-3 sm:grid-cols-2">{p.features.map(f=><div key={f} className="flex items-center gap-3 text-[13px]"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#0B4A2B] text-white"><Check size={13}/></span>{f}</div>)}</div><p className="mt-7 text-[11px] font-semibold uppercase tracking-[.13em] text-[#8f772f]">{p.availability}</p><Link href="/contact" className="mt-7 inline-flex w-fit items-center gap-2 rounded-xl bg-[#0B4A2B] px-6 py-4 text-[12px] font-bold text-white">Request Bulk Quote <ArrowRight size={14}/></Link></div></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></section><EnquirySection/></>}
